### ISSUE TITLE
data_input能发一份吗？

### ISSUE THREAD

**Issue by sarary** [InsaneLife/dssm#12]
邮箱是18366131461@163.com谢谢

**Comment by user8831222** [comment]
我也需要一份data_input，麻烦您可以发到我的邮箱吗，3012216039@tju.edu.cn，谢谢

**Comment by InsaneLife** [comment]
由于时间过长，代码api也有变化，假期会更新一版代码和数据，并说明环境。

**Comment by user8831222** [comment]
您好，方便的话，麻烦发下data_input代码，谢谢您！






发件人：AaronChou <notifications@github.com>
发送日期：2019-04-29 10:20:21
收件人：InsaneLife/dssm <dssm@noreply.github.com>
抄送人：user8831222 <3012216039@tju.edu.cn>,Comment <comment@noreply.github.com>
主题：Re: [InsaneLife/dssm] data_input能发一份吗？ (#12)
由于时间过长，代码api也有变化，假期会更新一版代码和数据，并说明环境。

**Comment by InsaneLife** [comment]
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。
