### ISSUE TITLE
Readme中loss指标训练数据和测试数据是一样的吗？

### ISSUE THREAD

**Issue by MC-Zealot** [InsaneLife/dssm#15]

**Comment by InsaneLife** [comment]
不一样。只是两者曲线很接近，下面是部分日志：
> Epoch #0 | Train Loss: 122.739 | PureTrainTime: 5.143s
> Epoch #0 | Test  Loss: 122.122 | Calc_LossTime: 1.320s
>
> Epoch #1 | Train Loss: 100.575 | PureTrainTime: 4.863s
> Epoch #1 | Test  Loss: 100.619 | Calc_LossTime: 0.992s
>
> Epoch #2 | Train Loss: 75.475 | PureTrainTime: 4.639s
> Epoch #2 | Test  Loss: 75.030 | Calc_LossTime: 1.031s
