### ISSUE TITLE
pull batch使用的是验证级的数据

### ISSUE THREAD

**Issue by MC-Zealot** [InsaneLife/dssm#16]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/7652307/57909282-f288aa80-78b4-11e9-9927-718ddeeeaffe.png">

pull batch的数据好像是写死成vali_data了。
你试试数据集分开跑一下。。

**Comment by InsaneLife** [comment]
是的，这块写错了，晚些会纠正，感谢指正。
