### ISSUE TITLE
为何用数据里的label？label表示“是否点击”，不是相似性

### ISSUE THREAD

**Issue by guotong1988** [InsaneLife/dssm#20]
![image](https://user-images.githubusercontent.com/4702353/62027032-4269e300-b20f-11e9-95d0-7f3f5c5b7f4e.png)

![image](https://user-images.githubusercontent.com/4702353/62027065-51e92c00-b20f-11e9-8393-1d127c432de5.png)

多谢！对么？
@InsaneLife 
这个任务是做啥的？

**Comment by guotong1988** [comment]
哦，，这里没用。
![image](https://user-images.githubusercontent.com/4702353/62027957-a8576a00-b211-11e9-8b5d-f2697770a6f3.png)

**Comment by InsaneLife** [comment]
建议看看数据预处理是怎么构建正负样本的。
