### ISSUE TITLE
i want to predict a query pair like "今天天气怎么样"  “今天温度怎么样” ，what to do?

### ISSUE THREAD

**Issue by yangyan1227** [InsaneLife/dssm#25]

**Comment by JNero** [comment]
+1 。怎么做预测？

**Comment by InsaneLife** [comment]
分别作为输入，获取输出句子的embedding向量，让后计算两个向量cos相似度即可。

**Comment by liuyangzy** [comment]
> 分别作为输入，获取输出句子的embedding向量，让后计算两个向量cos相似度即可。

如何输入

**Comment by InsaneLife** [comment]
需要先训练模型，然后做预测，训练入口：[train.py](https://github.com/InsaneLife/dssm/blob/master/train.py)
训练（默认使用功LCQMC数据集）：

```shell
python train.py --mode=train
```

预测：

```shell
python train.py --mode=train --file=$predict_file$
```

测试文件格式: q1\tq2, 例如：

```
今天天气怎么样	今天温度怎么样
```

**Comment by InsaneLife** [comment]
#29 #26

**Comment by InsaneLife** [comment]
> 需要先训练模型，然后做预测，训练入口：[train.py](https://github.com/InsaneLife/dssm/blob/master/train.py)
> 训练（默认使用功LCQMC数据集）：
> 
> ```shell
> python train.py --mode=train
> ```
> 
> 预测：
> 
> ```shell
> python train.py --mode=train --file=$predict_file$
> ```
> 
> 测试文件格式: q1\tq2, 例如：
> 
> ```
> 今天天气怎么样	今天温度怎么样
> ```

#29 #26
