### ISSUE TITLE
怎么做预测呀？ 

### ISSUE THREAD

**Issue by JNero** [InsaneLife/dssm#26]
作者， 这个预测怎么做呀

**Comment by liuyangzy** [comment]
同问，想知道代码里说的预测时只用输入query即可，将其embedding为向量。具体是怎么操作的

**Comment by InsaneLife** [comment]
需要先训练模型，然后做预测，训练入口：[train.py](https://github.com/InsaneLife/dssm/blob/master/train.py)

训练（默认使用功LCQMC数据集）：

```shell
python train.py --mode=train
```

预测：

```shell
python train.py --mode=train --file=$predict_file$
```

测试文件格式: q1\tq2, 例如：

```
今天天气怎么样	今天温度怎么样
```
