### ISSUE TITLE
代码有误？

### ISSUE THREAD

**Issue by sars715** [InsaneLife/dssm#28]
https://github.com/InsaneLife/dssm/blob/eefe42e3a4b2e688bf6624f561035300ae3f62ef/dssm_rnn.py#L78
这行应该写错了，bw这个没有用上

**Comment by InsaneLife** [comment]
> https://github.com/InsaneLife/dssm/blob/eefe42e3a4b2e688bf6624f561035300ae3f62ef/dssm_rnn.py#L78
> 
> 
> 这行应该写错了，bw这个没有用上

这个开始是准备用stack rnn进行实验，后来拖了。。。
