### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by zhongyunuestc** [InsaneLife/dssm#3]
你好，能否告知训练样本的格式是怎么样的呢（正负样本如何组织的，输入是一个query对应１个正样本，４个负样本吗），还有你中文特征提取是只用了uni_gramn吗，方便留个邮箱或者联系方式吗，谢谢（by the way,　我也是在成都哟，哈哈）

**Comment by InsaneLife** [comment]
word hash的格式，我用的uni-gram。so，这就是格式(我感觉很清晰了)。

**Comment by InsaneLife** [comment]
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。
