### ISSUE TITLE
损失函数的定义只涉及到了正样本？

### ISSUE THREAD

**Issue by ninesky110** [InsaneLife/dssm#35]
您好，我看代码里定义损失函数那一块，先对query分别和正样本负样本的out_embedding求cos，然后外接softmax之后，只用到了正样本的概率结果，为什么不把负样本的概率结果求负之后也加进来呢？

如果按照您的loss定义，那么完全可以舍去负样本的输入。

**Comment by ninesky110** [comment]
明白了  正样本的logit输出会受到负样本的影响，因为softmax的关系

**Comment by InsaneLife** [comment]
> 明白了 正样本的logit输出会受到负样本的影响，因为softmax的关系

是的
