### ISSUE TITLE
为什么训练出来一个epoch，loss就位0

### ISSUE THREAD

**Issue by chongqingwei** [InsaneLife/dssm#5]

**Comment by chongqingwei** [comment]
在训练的时候，loss很快就为0，auc就为1了。是哪里有问题呢？

**Comment by code-learner** [comment]
我也是这样，你找到原因了么？

**Comment by InsaneLife** [comment]
可以使用最新代码试试。
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。
