### ISSUE TITLE
why my train loss ,after 4or5 epoch ,softmax value equal nan。

### ISSUE THREAD

**Issue by chongqingwei** [InsaneLife/dssm#6]
为什么我的在训练5个epoch ，loss还在下降，但是输出的softmax的值都变味nan了。结果auc变味0.5了。

**Comment by InsaneLife** [comment]
原因可能会有很多，应该和具体数据相关。
ps: 
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。

**Comment by chongqingwei** [comment]
已经解决，感谢。




------------------ 原始邮件 ------------------
发件人: "AaronChou"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 晚上8:59
收件人: "InsaneLife/dssm"<dssm@noreply.github.com>;
抄送: "251132021"<251132021@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [InsaneLife/dssm] why my train loss ,after 4or5 epoch ,softmax value equal nan。 (#6)




原因可能会有很多，应该和具体数据相关。
 ps:
 由于之前代码api过时，已更新最新代码于：dssm_rnn.py
 
数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。

**Comment by InsaneLife** [comment]
能否分享一下原因和解决，供大家参考。

**Comment by InsaneLife** [comment]
出现NAN一般是由于分母出现0，或者log中出现非正数，可以采用截断(tf.clip_by_value)避免。

**Comment by DaBinGOGOGO** [comment]
你好，能说下具体怎么解决loss出现nan问题的吗? 我也遇到了，谢谢你

**Comment by chongqingwei** [comment]
首先确认样本正确性，其次不要用adam，用adgrad




发自我的iPhone

------------------ Original ------------------
