### ISSUE TITLE
data_input

### ISSUE THREAD

**Issue by zhaohongjie** [InsaneLife/dssm#7]
import data_input  ModuleNotFoundError:No module named 'data_input'
Where is the data_input

**Comment by iou2much** [comment]
同问，能否也附上实验的数据？谢谢

**Comment by ExpressGit** [comment]
data_input 各位老铁有拿到吗

**Comment by InsaneLife** [comment]
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。
