### ISSUE TITLE
datasets format problem

### ISSUE THREAD

**Issue by tzSmilence** [InsaneLife/dssm#9]
Can you tell me the datasets format or show a screenshot ?
In the following, you use data_sets.query_test_data, data_sets.doc_test_positive, data_sets.doc_test_negative, so I don't quite understand the format.
Thanks!

**Comment by sunjinguo** [comment]
I have the same doubt. Have you solved it?

**Comment by InsaneLife** [comment]
由于之前代码api过时，已更新最新代码于：dssm_rnn.py

数据处理代码data_input.py 和数据data 已经更新，由于使用了rnn，所以输入非bag of words方式。
